/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

generalSidebar: [
    'docs',
    {
      type: 'category',
      label: 'Discover Tella',
      link: {type: 'generated-index'},
      items: ['Discover Tella/features', 'Discover Tella/security-and-privacy', 'Discover Tella/accesibility', 'Discover Tella/user-stories'],
    },
    {
      type: 'category',
      label: 'Get Started',
      link: {type: 'doc', id: 'Get Started/get-started'},
      items: ['Get Started/get-started-android', 'Get Started/get-started-ios', 'Get Started/video-tutorials']
    },
    {
      type: 'category',
      label: 'For organizations',
      link: {type: 'generated-index'},
      items: ['For organizations/overview', 'For organizations/tella-web', 'For organizations/uwazi', 'For organizations/odk'],
    },
    {'Community': ['Community/community-meetings', 'Community/open-source', 'Community/translating-tella']},
    'faq',
    'privacy-policy',
    'releases'
  ],
};

module.exports = sidebars;
