---
name: "deploy"
on:
  push:
    branches:
    - "ci"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      PRODUCTION_URL: "https://tella-app.org/"
    steps:
    - uses: "actions/checkout@v7"
    - run: "npm install"
    - run: "npm run build"
  deploy:
    runs-on: "ubuntu-latest"
    needs: "build"
    steps:
    - uses: "burnett01/rsync-deployments@v9"
      with:
        switches: "-av --delete-after"
        path: "build/"
        remote_path: "/"
        remote_host: "tella-app.org"
        remote_port: 22
        remote_user: "tella-app--org"
        remote_key: "${{ secrets.PRIVATE_KEY }}"
